# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 593)
        MainWindow.setStyleSheet("background-color: #EEF1DA")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QComboBox::drop-down {\n"
"    border: none;\n"
"    background: #AAB99A; \n"
"    width: 30px;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #2980b9;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.weight_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.weight_input.setGeometry(QtCore.QRect(170, 110, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.weight_input.setFont(font)
        self.weight_input.setStyleSheet("border: 2px solid #AAB99A;\n"
"border-radius: 10px;\n"
"padding: 5px;\n"
"background-color: #EEF1DA;\n"
"font-size: 14px;\n"
"color: #333;")
        self.weight_input.setText("")
        self.weight_input.setFrame(False)
        self.weight_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weight_input.setPlaceholderText("")
        self.weight_input.setObjectName("weight_input")
        self.label1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(100, 160, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(100, 100, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.bmi_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.bmi_label.setGeometry(QtCore.QRect(290, 280, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.bmi_label.setFont(font)
        self.bmi_label.setText("")
        self.bmi_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bmi_label.setObjectName("bmi_label")
        self.underweight_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.underweight_label.setGeometry(QtCore.QRect(70, 460, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        self.underweight_label.setFont(font)
        self.underweight_label.setStyleSheet("background-color: rgb(255, 210, 10);\n"
"border-radius: 12px;\n"
"font-weight: bold;\n"
"border: 2px solid #AAB99A;\n"
"")
        self.underweight_label.setObjectName("underweight_label")
        self.normal_weight_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.normal_weight_label.setGeometry(QtCore.QRect(240, 460, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        self.normal_weight_label.setFont(font)
        self.normal_weight_label.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(21, 170, 10);\n"
"font-weight: bold;\n"
"border: 2px solid #AAB99A;\n"
"")
        self.normal_weight_label.setWordWrap(False)
        self.normal_weight_label.setObjectName("normal_weight_label")
        self.overweight_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.overweight_label.setGeometry(QtCore.QRect(410, 460, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        self.overweight_label.setFont(font)
        self.overweight_label.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(255, 90, 5);\n"
"font-weight: bold;\n"
"border: 2px solid #AAB99A;")
        self.overweight_label.setObjectName("overweight_label")
        self.obese_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.obese_label.setGeometry(QtCore.QRect(580, 460, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        self.obese_label.setFont(font)
        self.obese_label.setStyleSheet("background-color: #FF0000;\n"
"border-radius: 12px;\n"
"font-weight: bold;\n"
"border: 2px solid #AAB99A;")
        self.obese_label.setObjectName("obese_label")
        self.measurement_system = QtWidgets.QComboBox(parent=self.centralwidget)
        self.measurement_system.setGeometry(QtCore.QRect(170, 50, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(-1)
        font.setBold(True)
        self.measurement_system.setFont(font)
        self.measurement_system.setStyleSheet("font-weight: bold;\n"
"border: 2px solid #AAB99A;\n"
"border-radius: 10px;\n"
"padding: 5px;\n"
"background-color: #EEF1DA;\n"
"font-size: 14px;\n"
"color: #333;")
        self.measurement_system.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.measurement_system.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
        self.measurement_system.setObjectName("measurement_system")
        self.measurement_system.addItem("")
        self.measurement_system.addItem("")
        self.label3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(100, 40, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.units_weight = QtWidgets.QLabel(parent=self.centralwidget)
        self.units_weight.setGeometry(QtCore.QRect(390, 110, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        self.units_weight.setFont(font)
        self.units_weight.setObjectName("units_weight")
        self.units_height = QtWidgets.QLabel(parent=self.centralwidget)
        self.units_height.setGeometry(QtCore.QRect(390, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        self.units_height.setFont(font)
        self.units_height.setObjectName("units_height")
        self.height_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.height_input.setGeometry(QtCore.QRect(170, 170, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.height_input.setFont(font)
        self.height_input.setStyleSheet("border: 2px solid #AAB99A;\n"
"border-radius: 10px;\n"
"padding: 5px;\n"
"background-color: #EEF1DA;\n"
"font-size: 14px;\n"
"color: #333;")
        self.height_input.setText("")
        self.height_input.setFrame(False)
        self.height_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.height_input.setPlaceholderText("")
        self.height_input.setObjectName("height_input")
        self.calculate_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculate_button.setGeometry(QtCore.QRect(520, 140, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        self.calculate_button.setFont(font)
        self.calculate_button.setStyleSheet("border-radius: 15px;\n"
"background-color: #E1EACD;\n"
"border: 2px solid #AAB99A;")
        self.calculate_button.setFlat(True)
        self.calculate_button.setObjectName("calculate_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionClear = QtGui.QAction(parent=MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "Height:"))
        self.label2.setText(_translate("MainWindow", "Weight:"))
        self.underweight_label.setText(_translate("MainWindow", "         Underweight\n"
"              < 18.5"))
        self.normal_weight_label.setText(_translate("MainWindow", "        Normal Weight\n"
"             18.5 - 25"))
        self.overweight_label.setText(_translate("MainWindow", "           Overweight\n"
"                25-30"))
        self.obese_label.setText(_translate("MainWindow", "               Obese\n"
"                > 30"))
        self.measurement_system.setCurrentText(_translate("MainWindow", "Metric"))
        self.measurement_system.setItemText(0, _translate("MainWindow", "Metric"))
        self.measurement_system.setItemText(1, _translate("MainWindow", "Imperial"))
        self.label3.setText(_translate("MainWindow", "System:"))
        self.units_weight.setText(_translate("MainWindow", "kg"))
        self.units_height.setText(_translate("MainWindow", "cm"))
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
